# Generated by Django 2.2.4 on 2019-08-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("header", models.CharField(max_length=128, verbose_name="header")),
                ("text", models.TextField(verbose_name="text")),
                ("picture", models.ImageField(upload_to="", verbose_name="image")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation date"
                    ),
                ),
            ],
            options={"verbose_name": "article", "verbose_name_plural": "articles"},
        )
    ]
